# Note that the testing module branch
# is only included if the workflow is
# executed in testing mode
include: "rules/commons/00_commons.smk"

if not RUN_IN_TEST_MODE:
    include: "rules/00_modules.smk"
    include: "rules/99_aggregate.smk"
else:
    logerr("DEBUG: test run detected - workflow module include skipped")


rule run_all:
    """
    This is the default target rule to trigger
    the execution of all rules in the workflow.
    The 'run_all' rule includes the following three
    templated workflow tasks:
    1. dump the workflow config object into the results/ folder
    2. copy the sample sheet into the results/ folder (if applicable)
    3. create the workflow manifest file in the results/ folder (if applicable)

    The object 'WORKFLOW_OUTPUT' is a simple list containing all
    workflow outputs (files). This list is created in the module
    rules::commons::99_aggregate.smk
    """
    input:
        RUN_CONFIG_RELPATH,
        COPY_SAMPLE_SHEET_RELPATH,
        MANIFEST_RELPATH,
        WORKFLOW_OUTPUT,


rule run_all_no_manifest:
    """ Rule added for the
    unexpected case that no
    manifest file shall be
    created (e.g., testing)
    Part of gh#15 fix.
    """
    input:
        RUN_CONFIG_RELPATH,
        COPY_SAMPLE_SHEET_RELPATH,
        WORKFLOW_OUTPUT,


rule run_tests:
    input:
        RUN_CONFIG_RELPATH,
        COPY_SAMPLE_SHEET_RELPATH,
        MANIFEST_RELPATH,
        WORKFLOW_OUTPUT


rule run_tests_no_manifest:
    input:
        RUN_CONFIG_RELPATH,
        COPY_SAMPLE_SHEET_RELPATH,
        WORKFLOW_OUTPUT


rule run_build_docs:
    retries: 0
    run:
        global DOC_RECORDER
        try:
            DOC_RECORDER.generate_documentation()
        except Exception as err:
            logerr(f"Auto-generating the workflow documentation failed: {str(err)}")
            raise
        else:
            logout(f"Auto-generating the workflow documentation was successful.")


onsuccess:
    if any([DIR_CLUSTERLOG_OUT.is_dir(), DIR_CLUSTERLOG_ERR.is_dir()]):
        shell(f"rm -rf {DIR_CLUSTERLOG_OUT} && mkdir -p {DIR_CLUSTERLOG_OUT}")
        shell(f"rm -rf {DIR_CLUSTERLOG_ERR} && mkdir -p {DIR_CLUSTERLOG_ERR}")
    shell(f"rm -f {RUN_CONFIG_RELPATH.with_suffix('.bak.yaml')}")
    shell(f"rm -f {_SMK_CLI_CAPTURE_CACHE_FILE}")


onerror:
    try:
        rsync_f2f(RUN_CONFIG_RELPATH, RUN_CONFIG_RELPATH.with_suffix(".bak.yaml"))
    except FileNotFoundError:
        # can happen when creation of a single file is requested
        # during development
        pass
    shell(f"rm -f {RUN_CONFIG_RELPATH}")
    shell(f"rm -f {_SMK_CLI_CAPTURE_CACHE_FILE}")


# Documentation for the main workflow
# target rules

_THIS_MODULE = ["Snakefile"]
_THIS_CONTEXT = DocContext.TEMPLATE

DOCREC.add_module_doc(_THIS_CONTEXT, _THIS_MODULE)

DOCREC.add_rule_doc(rules.run_all.rule)
